# Generated by Django 2.2.4 on 2020-12-23 10:41

from django.db import migrations


def set_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    separator_year = 2015
    for flat in Flat.objects.all():
        if flat.construction_year < separator_year:
            flat.new_building = False
        else:
            flat.new_building = True
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building),
    ]
