# Generated by Django 2.2.4 on 2021-01-20 12:52

from django.db import migrations
import phonenumbers

def set_normalized_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        standardized_phone = phonenumbers.format_number(parsed_phone, phonenumbers.PhoneNumberFormat.E164)
        flat.owner_pure_phone = standardized_phone
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(set_normalized_phone),
    ]
