# Generated by Django 2.2.4 on 2021-01-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210128_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(to='property.Owner', verbose_name='Собственники'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_flats',
            field=models.ManyToManyField(to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
