# Generated by Django 2.2.4 on 2021-01-29 14:17

from django.db import migrations


def set_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner,
                                    owner_pure_phone=flat.owner_pure_phone,
                                    defaults={
                                        'owners_phonenumber': flat.owners_phonenumber,
                                    })

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20210128_2027'),
    ]

    operations = [
        migrations.RunPython(set_flats_to_owners),
    ]
